version: '3'
services:
  bodypix:
    build: ./bodypix/
    ports:
      - "9000:9000"
  fakecam:
    build: ./fakecam/
    ports:
      - "8080:8080"
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video20:/dev/video20"